'use strict';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=s=>{try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:'#';}catch{return '#';}};
const T=(o,k)=>{const v=o?.[k+'_zh']??o?.[k]??o?.[k+'_en']??'';return Array.isArray(v)?v.map(zh):zh(v);};
const zh=v=>typeof v==='string'?(fieldZH[v]||v.replace(/^Official personnel announcement · /,'官方任免公告 · ')):v;
const fieldZH={"Article URL date; verify against the original notice":"日期取自文章链接，仍需对照原文","Official personnel index publication date":"日期取自官方任免栏目","Not independently established":"尚未单独核准","Use a dated article link from the official 12371 personnel feed.":"请使用 12371 官方任免栏目中带日期的文章链接。","Choose an official 12371 article URL from the personnel feed.":"请使用 12371 官方任免栏目的文章链接。","Review and select at least one appointment.":"请核对并勾选至少一条任免。","No supported appointment clauses found. Open the source and use Codex to review its wording; nothing was imported.":"未识别到支持的任免句式。可打开原文交给 Codex 核对；尚未导入。","Add an English job title for every selected entry.":"请为勾选项填写英文职务对照。","The review changed. Reopen it before applying.":"核对记录已变化，请重新打开后再入库。","This profile changed after review. Prepare a fresh review before applying.":"人物档案已变化，请重新读取公告后再入库。","This is an older notice. Preserve the current profile and record it as historical.":"这是一份较早公告，请保留现任档案，并将此条记入历史。","This older appointment does not establish current service. Record it as historical.":"较早任命不能证明目前仍在任，请记入历史。",'尚未单独核准':'尚未单独核准','Effective date not stated; announcement date is recorded separately.':'公告未明确生效日，另行记录公告日期。','The notice establishes removal from an office, not the full tenure or personal rank.':'这份公告确认免职；完整任期和个人级别尚未核准。','Only explicit personal rank in the announcement is recorded. An earlier appointment alone does not establish current service.':'只记录公告明确说明的个人级别。旧任命不能单独证明目前仍在任。','Institution recorded in an appointment notice; mandate not yet documented':'已从任免公告录入，机构职责待补充','No reporting line is inferred from the appointment notice.':'任免公告本身不证明机构隶属关系。'};
const trackName=k=>({party:'党',state:'国家机关',military:'军事',consultative:'政协',regulator:'监管机构',sector:'行业示意',democratic_party:'民主党派'})[k]||k;
let atlas=null,focus='all',query='',route='map',news={items:[],loading:true},newsScope='central',requestText='';
let peopleLevel='all',peopleTrack='all',peopleStatus='all',peopleOrg='all';
const economy=new Set(['state_council','central_financial_economic_commission','central_financial_economic_office','central_financial_commission','central_financial_office','central_financial_work_commission','pboc','nfra','csrc','mof','mofcom','ndrc','miit','nda','sasac','sta','foreign_affairs','foreign_affairs_office','trade_representative','mfa']);
const org=id=>atlas.institutions.find(x=>x.id===id),person=id=>atlas.people.find(x=>x.id===id);
const current=p=>p.roles.filter(r=>r.status==='current');
const members=id=>atlas.people.filter(p=>current(p).some(r=>r.org_id===id||(id==='politburo'&&r.org_id==='politburo_standing')));
const match=x=>!query||JSON.stringify(x).toLowerCase().includes(query.toLowerCase());
const external=(url,label)=>`<a href="${esc(safeURL(url))}" target="_blank" rel="noopener noreferrer">${esc(label)} ↗</a>`;
const personLabel=p=>p.name+(atlas.people.some(other=>other.id!==p.id&&other.name===p.name)?'（'+(p.birth_year?p.birth_year+'年生':mainRole(p))+'）':'');
const names=ps=>ps.map(p=>`<button class="person-chip" data-person="${esc(p.id)}">${esc(personLabel(p))}</button>`).join('');
const paragraphs=text=>String(text||'').split(/\n\s*\n/).map(p=>`<p>${esc(p)}</p>`).join('');
function sources(ids,open=false){const ss=[...new Set(ids||[])].map(id=>atlas.sources.find(x=>x.id===id)).filter(Boolean);return `<details class="sources" ${open?'open':''}><summary>来源 · ${ss.length}</summary><ol>${ss.map(s=>`<li>${external(s.url,T(s,'title'))}<small>${s.published_at?esc(s.published_at)+' · ':''}核对 ${esc(s.accessed_at||'日期未录入')}</small>${s.has_local_evidence?`<button class="text-button" data-evidence="${esc(s.id)}">${isPublicAtlas()?'核对摘录':'本地核对摘录'} →</button>`:''}</li>`).join('')}</ol></details>`;}
function roleTracks(r){const k=org(r.org_id)?.kind,title=r.title_en||r.title;if(k==='military')return ['military',/CPC|中国共产党|中共中央/.test(title+r.title)?'party':'state'];if(/党组|党委|党工委|党支部/.test(r.title)||/Party (Committee|Members Group)/.test(title)){const combined=k!=='party'&&(/Party.*\band (Director|Minister|Governor|Chair)/.test(title)||/(?:党组|党委).*?(?:、|兼任|兼|和).*(?:局长|主任|部长|行长)/.test(r.title));return combined?['party','state']:['party'];}return [k==='democratic_party'?'democratic_party':k==='party'?'party':k==='consultative'?'consultative':'state'];}
const roleTrack=r=>roleTracks(r).join(' / ');
const bands=[['national-principal','国家级正职岗位'],['national-deputy','国家级副职岗位'],['national-unverified','国家领导岗位 · 个人级别待核'],['ministerial','省部级正职'],['deputy-ministerial','省部级副职岗位'],['departmental-principal','厅局级正职岗位'],['departmental-deputy','厅局级副职岗位'],['county-principal','县处级正职岗位'],['county-deputy','县处级副职岗位'],['township-principal','乡科级正职岗位'],['township-deputy','乡科级副职岗位'],['unclassified','层级尚未核准'],['uncertain','任职状态待复核'],['historical','历史人物']];
function band(p){const rs=current(p);if(!rs.length)return personStatus(p)==='uncertain'?'uncertain':'historical';if(rs.some(r=>r.org_id==='politburo_standing'||r.org_id==='general_secretary'))return 'national-principal';if(rs.some(r=>['politburo','central-secretariat','supreme_court','supreme_procuratorate'].includes(r.org_id)||(['state-president','state_council','cmc','nsc'].includes(r.org_id)&&/Vice Premier|State Councilor|Vice Chairman|Director/.test(r.title_en||r.title))))return 'national-deputy';if(rs.some(r=>r.org_id==='state-president'))return 'national-unverified';if(rs.some(r=>r.office_band==='provincial-ministerial-principal'))return 'ministerial';if(rs.some(r=>/Full (provincial\/ministerial|ministerial)|Personal rank: full ministerial|Ministerial rank \(explicit/i.test(r.rank_en||r.rank)))return 'ministerial';if(rs.some(r=>/^(Vice Minister|Deputy Director|Deputy Governor)$/.test(r.title_en||r.title)&&['miit','mara','moe','moj','pboc','nfra','csrc','cac'].includes(r.org_id)))return 'deputy-ministerial';const mapped=rs.map(r=>r.office_band).map(b=>b==='provincial-ministerial-deputy'?'deputy-ministerial':b);return bands.find(([id])=>mapped.includes(id))?.[0]||'unclassified';}
const bandLabel=p=>bands.find(([id])=>id===band(p))[1];
function mainRole(p){const rs=current(p);const r=rs.find(r=>r.org_id==='general_secretary')||rs.find(r=>!['politburo','politburo_standing','central_committee','central-secretariat'].includes(r.org_id)&&roleTrack(r)!=='party')||rs[0]||p.roles.find(r=>/^(国务院总理|中共中央总书记|中共中央军委主席|中央军委主席)$/.test(r.title))||p.roles[0];if(!r)return '';let title=T(r,'title');const o=org(r.org_id);if(o&&/^(部长|主任|主席|行长|局长|书记|副书记|副部长|副主任|副主席|副行长|副局长|委员|副委员长|总理|副总理|省长|市长|国务委员)$/.test(title))title=o.name+' · '+title;return (rs.length?'':r.status==='former'?'前':'记录：')+title+(!rs.length&&r.since?'（'+r.since+(r.until?'—'+r.until:'')+'）':'');}
function orgCard(id,small=false){const o=org(id);if(!o)return '';const ps=members(id);return `<article class="org-card ${small?'compact':''}" data-kind="${esc(o.kind)}"><button class="org-open" data-org="${esc(id)}"><small lang="en">${esc(o.name_en||'')}</small><h3>${esc(o.name)}</h3><span class="org-level">${esc(T(o,'level_label'))}</span><span class="open-arrow" aria-hidden="true">↗</span></button>${ps.length?`<div class="people-inline">${names(ps)}</div>`:''}</article>`;}
function selectBox(id,label,options,value){return `<label>${esc(label)}<select id="${esc(id)}">${options.map(([v,t])=>`<option value="${esc(v)}" ${value===v?'selected':''}>${esc(t)}</option>`).join('')}</select></label>`;}
function personCard(p){const tracks=[...new Set(current(p).flatMap(roleTracks))];return `<button class="person-card ${current(p).length?'':'historical'}" data-person="${esc(p.id)}"><span class="mini-label">${esc(bandLabel(p))}</span><h3>${esc(personLabel(p))} <small>${esc(p.name_en||'')}</small></h3><p>${esc(mainRole(p))}</p>${verificationSummary(p)}<span class="card-footer"><span>${esc(tracks.map(t=>trackName(t)).join(' · ')||'历史任职')}${p.personal_note?' · 有笔记':''}</span><span>↗</span></span></button>`;}
function drawPeople(){const ps=atlas.people.filter(p=>(match(p)||careerPosts(p.id).some(match))&&(peoplePlace==='all'||servicePlaces(p,peopleRegionMode).includes(peoplePlace))&&(focus==='all'||p.roles.some(r=>(peopleStatus!=='current'||r.status==='current')&&economy.has(r.org_id)))&&matchesEvidenceFilter(p,peopleSector,peopleVerification)&&(peopleLevel==='all'||band(p)===peopleLevel)&&(peopleStatus==='all'||personStatus(p)===peopleStatus)&&(peopleTrack==='all'||p.roles.some(r=>(peopleStatus!=='current'||r.status==='current')&&roleTracks(r).includes(peopleTrack)))&&(peopleOrg==='all'||p.roles.some(r=>r.org_id===peopleOrg&&(peopleStatus!=='current'||r.status==='current'))));
 const controls=selectBox('people-level','现任岗位层级',[['all','所有层级'],...bands],peopleLevel)+selectBox('people-track','体系',[['all','党与国家机关'],['party','党'],['state','国家机关'],['consultative','政协'],['military','军事'],['democratic_party','民主党派']],peopleTrack)+selectBox('people-status','任职状态',[['all','所有记录'],['current','有现任资料'],['uncertain','状态待复核'],['historical','已知曾任人物']],peopleStatus)+selectBox('people-org','机构',[['all','所有机构'],...atlas.institutions.filter(o=>atlas.people.some(p=>p.roles.some(r=>r.org_id===o.id))).sort((a,b)=>a.name.localeCompare(b.name,'zh-CN')).map(o=>[o.id,o.name])],peopleOrg)+selectBox('people-place','任职地区',[['all','所有地区'],...(atlas.locations||[]).filter(l=>l.id!=='china').map(l=>[l.id,l.name])],peoplePlace)+(peoplePlace!=='all'?selectBox('people-region-mode','地区经历',[['any','在此任职的全部经历'],['current','现任在此'],['past','曾在此工作']],peopleRegionMode):'');
 const activeFilters=[peopleLevel,peopleTrack,peopleStatus,peopleOrg,peoplePlace,peopleSector,peopleVerification].filter(v=>v!=='all').length;return `<details class="people-filters" id="people-filters" ${(peopleFiltersOpen??!compactScreen())?'open':''}><summary>筛选${activeFilters?' · '+activeFilters+' 项':''}</summary><div class="filter-row">${controls}</div>${evidenceControls('people',peopleSector,peopleVerification)}</details><div class="section-title people-count"><p class="note compact-note">${ps.length} / ${atlas.people.length} 条档案 · 按现任岗位层级排列</p><div class="detail-actions"><button id="clear-people-filters">重置筛选</button><button id="add-profile-request">补充人物 / 履历</button><a href="/api/export" download="china-atlas.json">导出数据库 ↓</a></div></div><p class="note compact-note">层级用于浏览；机构规格、岗位层级与个人级别分开记录。 <button class="text-button" data-guide="reading-leadership-ranks">如何理解层级 →</button></p>${bands.map(([id,title])=>{const group=ps.filter(p=>band(p)===id);return group.length?`<section class="map-section"><div class="section-title"><h2>${esc(title)}</h2><span>${group.length} 人</span></div><div class="person-grid">${group.map(personCard).join('')}</div></section>`:'';}).join('')||'<p class="empty">没有符合筛选的人物。</p>'}`;
}
function eventCard(e){return `<article class="event"><time>${esc(e.date)}</time><div><span class="mini-label">${e.status==='verified'?'有来源的任免记录':'未经核实的解释'}</span><h3>${esc(T(e,'title'))}</h3>${paragraphs(T(e,'description'))}<div class="people-inline">${names((e.person_ids||[]).map(person).filter(Boolean))}</div>${sources(e.source_ids)}</div></article>`;}
function courseRefs(g){return (g.course_refs||[]).map(r=>{const d=atlas.documents.find(d=>d.id===r.document_id);return `<button class="course-ref" data-document="${esc(r.document_id)}">${esc(d?T(d,'title'):r.document_id)} · 第 ${esc(r.slides.join(', '))} →</button>`;}).join('');}
function guideDetail(g){return `<article class="guide-card" id="guide-${esc(g.id)}"><span class="mini-label">${g.course_refs?'OXFORD 课程 · 阅读笔记':'制度笔记'}</span><h2>${esc(T(g,'title'))}</h2>${paragraphs(T(g,'body'))}${T(g,'learning_question')?`<blockquote>${esc(T(g,'learning_question'))}</blockquote>`:''}${courseRefs(g)}${T(g,'historical_note')?`<p class="note">${esc(T(g,'historical_note'))}</p>`:''}${g.id==='accuracy-methodology'?`<div class="detail-actions">${external('https://github.com/taiwu2022/ChinaAtlas/blob/codex/mobile-pages/docs/SOURCE_SEARCH_METHODS.md','来源与检索清单')}${external('https://github.com/taiwu2022/ChinaAtlas/blob/codex/mobile-pages/docs/ACCURACY_REPORT.md','本次复核报告')}${external('https://github.com/taiwu2022/ChinaAtlas/blob/codex/mobile-pages/docs/ACCURACY_METHOD.md','完整核验方法')}</div>`:''}${g.source_ids?.length?sources(g.source_ids):''}</article>`;}
function drawGuide(){if(isPublicAtlas())return drawPublicGuide();const ranked=atlas.rank_mapping||[],courses=atlas.guides.filter(g=>g.course_refs&&match(g)),other=atlas.guides.filter(g=>!g.course_refs&&match(g));return `<section class="rank-guide"><div class="section-title"><h2>职务层级与交叉任职</h2><a href="#map">查看制度图 →</a></div><div class="rank-ladder">${ranked.map((r,i)=>`<div><small>${String(i+1).padStart(2,'0')}</small><strong>${esc(r.label_zh)}</strong><span lang="en">${esc(r.label_en)}</span></div>`).join('')}</div><p class="note">党内身份、职务层级、地方行政层级不是一回事。同一个人可以兼任党和国家机关的多个职务。</p>${sources(ranked.flatMap(r=>r.definition_source_ids))}</section><section class="map-section"><div class="section-title"><h2>你的 Oxford 政治课程</h2><span>2023 年课程 · 当时的人事资料</span></div><div class="document-grid">${(atlas.documents||[]).filter(match).map(d=>`<button class="document-card" data-document="${esc(d.id)}"><span class="mini-label">OXFORD · ${d.year}</span><h3>${esc(T(d,'title'))}</h3><span>${d.slides.length} 条课件笔记 →</span></button>`).join('')}</div></section><div class="guide-grid">${courses.map(g=>`<button class="guide-preview" data-guide="${esc(g.id)}"><span class="mini-label">阅读笔记</span><h3>${esc(T(g,'title'))}</h3><p>${esc(T(g,'learning_question')||String(T(g,'body')).split('\n')[0])}</p><span>阅读与查看来源 →</span></button>`).join('')}</div><section class="map-section reference-notes"><div class="section-title"><h2>参考条目</h2><span>机构、职责与资料方法</span></div>${other.map(g=>`<details class="reference-item"><summary>${esc(T(g,'title'))}</summary>${guideDetail(g)}</details>`).join('')}</section><p class="note">旧课件用来理解制度；现任人物以档案中的新近来源为准。这个库会逐步补充。</p>`;}
function render(){if(!atlas)return;route=hashParts().page;if(!['map','people','regions','network','changes','guide'].includes(route))route='map';document.querySelectorAll('nav a').forEach(a=>{const active=a.hash==='#'+route;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.querySelectorAll('[data-focus]').forEach(b=>b.classList.toggle('selected',b.dataset.focus===focus));$('heading').textContent={map:'当前制度结构',people:'人物与履历',changes:'谁上任，谁离任',guide:'制度与阅读',network:'人物关系网',regions:'地方人物'}[route];document.querySelector('.segments').hidden=route!=='people';$('search').placeholder={map:'搜索机构或岗位…',people:'姓名、职务、曾任地区…',changes:'搜索任免…',guide:'搜索制度笔记…',network:'搜索关联人物…',regions:'搜索本地区人物或履历…'}[route];$('content').innerHTML=({map:drawMap,people:drawPeople,changes:drawChanges,guide:drawGuide,network:drawNetwork,regions:drawRegions})[route]();publicModeUI();if(route==='network')syncNetworkAddress();if(route==='map')requestAnimationFrame(finishGraph);rememberReadingPosition();}
function showDetail(html,kind){$('detail-body').innerHTML=(navigationReady?'<button class="detail-back" id="detail-back">← 返回</button>':'')+html;$('detail').setAttribute('aria-label',kind==='person'?'人物档案':kind==='org'?'机构详情':kind==='review'?'核对任免公告':'阅读详情');if(!$('detail').open)$('detail').showModal();$('detail').scrollTop=0;}
const profileFactLabels={birth_date:'出生年月',native_place:'籍贯',education:'教育',work_started:'参加工作',party_joined:'加入中共',career_background:'历史经历'};
function profileFacts(p){const facts=(atlas.profile_facts||[]).filter(f=>f.person_id===p.id);if(!facts.length)return '';return `<section class="profile-facts"><div class="section-title"><h3>背景资料</h3><button class="text-button" data-guide="accuracy-methodology">核验方法 →</button></div><div class="fact-grid">${facts.map(f=>`<article class="profile-fact"><span class="mini-label">${esc(f.label||profileFactLabels[f.field]||f.field)}</span><p>${esc(f.value)}</p><details><summary>${esc(({verified:'原文支持',unverified:'未核实',conflicting:'来源冲突'})[f.evidence_status]||'待复核')} · 查看依据</summary><blockquote>${esc(f.evidence_excerpt||'摘录待补充')}</blockquote><p class="note">来源时点 ${esc(f.as_of_date||'未注明')} · 核对 ${esc(f.reviewed_at||'未注明')}</p>${f.note?`<p class="note">${esc(f.note)}</p>`:''}${sources(f.source_ids,true)}</details></article>`).join('')}</div></section>`;}
function showPerson(id){const p=person(id);if(!p)return;const rs=[...p.roles].sort((a,b)=>(b.status==='current')-(a.status==='current'));showDetail(`${profileHeading(p)}<div class="detail-actions"><button class="primary" data-network-person="${esc(id)}">关系与足迹</button><button data-person-map="${esc(id)}">职务图</button><button data-copy-person="${esc(id)}">分享人物</button><button data-ask="person:${esc(id)}">复制 AI 问题</button></div>${p.profile_status==='appointment_only'?'<p class="note">从任免公告录入。其他兼任职务与早期履历尚待补充。</p>':''}${p.identity_note?`<p class="identity-note">${esc(p.identity_note)}</p>`:''}${p.possible_identity_ids?.length?`<details class="sources"><summary>同名记录 · 身份尚未合并</summary>${p.possible_identity_ids.map(id=>person(id)).filter(Boolean).map(other=>`<button class="text-button" data-person="${esc(other.id)}">${esc(other.name)} · ${esc(mainRole(other))} →</button>`).join('')}</details>`:''}<h3>职务 · ${esc(bandLabel(p))}</h3><div class="roles">${rs.map(r=>`<article class="role"><span class="badge ${r.status==='current'?'':'former'}">${esc(evidenceLabels[roleEvidence(r)]||'待复核')}</span> <span class="mini-label">${esc(roleTracks(r).map(trackName).join(' / '))}</span><h4>${esc(T(r,'title'))}</h4><button class="text-button" data-org="${esc(r.org_id)}">${esc(org(r.org_id)?.name||r.org_id)} →</button><p>${r.as_of_date?'资料时点 '+esc(r.as_of_date)+' · ':''}${r.since?'起始 '+esc(r.since):'起始日期未单独核准'}${r.until?' — '+esc(r.until):''}${r.announced_at?' · 任命公告 '+esc(r.announced_at):''}${r.ended_announced_at?' · 免职公告 '+esc(r.ended_announced_at):''}</p><p class="role-rank">层级 / 职衔： ${esc(T(r,'rank')||'尚未单独核准')}</p>${T(r,'note')||r.date_note?`<p class="note">${esc(T(r,'note')||r.date_note)}</p>`:''}<details><summary>依据与原文</summary><p class="note">${esc(T(r,'rank_basis'))}</p><p lang="zh">${esc(r.title)}</p>${sources(r.source_ids,true)}</details></article>`).join('')}</div>${(T(p,'focus')||[]).length?`<h3>关注职责</h3><ul>${T(p,'focus').map(t=>`<li>${esc(t)}</li>`).join('')}</ul>`:''}${profileFacts(p)}<h3>地区与任职足迹</h3><div class="place-tags">${personPlaces(id).map(pid=>`<button data-place="${esc(pid)}">${esc(place(pid)?.name||pid)}</button>`).join('')}</div>${profileCareerTimeline(p)}<h3>我的笔记</h3>${isPublicAtlas()?'<p class="note compact-note">仅保存在当前浏览器；可在“我的笔记”导出、导入。</p>':''}<label for="person-note" class="sr-only">个人笔记</label><textarea id="person-note" placeholder="记下疑问、阅读联想或待核实的线索…">${esc(p.personal_note||'')}</textarea><button data-save-note="${esc(id)}">保存笔记</button><p class="note">履历为已核对片段；共事经历本身不能说明私人关系或任用原因。</p>${sources(p.source_ids)}`,'person');}
function showOrg(id){const o=org(id);if(!o)return;const ps=members(id),rels=atlas.relations.filter(r=>r.from===id||r.to===id);showDetail(`<span class="pill">机构 / ${esc(trackName(o.kind))}</span><h2 class="detail-title">${esc(o.name)}</h2><p class="detail-subtitle" lang="en">${esc(o.name_en||'')}</p><p class="level-band">${esc(T(o,'level_label'))}</p><div class="detail-actions"><button class="primary" data-ask="org:${esc(id)}">复制 AI 问题</button><button data-view-org-people="${esc(id)}">查看人物</button></div>${ps.length?`<h3>已录入的现任人物</h3><div class="people-inline large">${names(ps)}</div>`:''}<h3>职责与权限</h3><ul>${[...(T(o,'duties')||[]),...(T(o,'authority')||[])].map(t=>`<li>${esc(t)}</li>`).join('')}</ul><h3>如何理解边界</h3><ul>${(T(o,'limits')||[]).map(t=>`<li>${esc(t)}</li>`).join('')}</ul>${rels.length?`<h3>机构关系</h3><div class="connections">${rels.map(r=>{const outward=r.from===id,other=org(outward?r.to:r.from);return `<article><span class="connection-label">${esc(T(r,'label'))}</span><button data-org="${esc(other.id)}">${outward?'→':'←'} ${esc(other.name)}</button>${sources(r.source_ids)}</article>`;}).join('')}</div>`:''}${sources(o.source_ids)}`,'org');}
function showGuide(id){const g=atlas.guides.find(g=>g.id===id);if(g)showDetail(guideDetail(g),'guide');}
function showDocument(id){const d=atlas.documents.find(d=>d.id===id);if(!d)return;showDetail(`<span class="pill">OXFORD · ${d.year} · 历史教学资料</span><h2 class="detail-title">${esc(T(d,'title'))}</h2><p class="note">来自你的原课件。课件中的人数和名单反映的是当时情况。</p><button class="primary" data-open-document="${esc(id)}">打开原课件 ↗</button><ol class="timeline">${d.slides.map(s=>`<li><time>第 ${s.number} 页</time><h3>${esc(T(s,'title'))}</h3><p>${esc(T(s,'summary'))}</p></li>`).join('')}</ol>`,'guide');}
function showAsk(kind,id){const p=kind==='person'?person(id):org(id),ss=(p.source_ids||[]).map(id=>atlas.sources.find(s=>s.id===id)).filter(Boolean);requestText=`我在 China Atlas 读到了${p.name}（${p.name_en||''}）。请核对职务和职责，再用直接、简明的中文解释其在中国政治与经济决策中的位置。结合有来源的履历或政策案例，区分正式权限、可观察事实与推测；不要由共同任职经历推断私人关系、派系或任用原因。\n\n当前资料页：${location.href}\n资料核对日期：${atlas.verified_at}\n来源：\n${ss.map(s=>T(s,'title')+' '+s.url).join('\n')}`;showDetail(`<span class="pill">与 CODEX 讨论</span><h2 class="detail-title">${esc(p.name)}</h2><label for="ask-question">你的问题 · 中英文均可</label><textarea id="ask-question" placeholder="这段履历说明了什么？哪些关系还需要证据？"></textarea><p class="note">复制后，粘贴到当前 Codex 对话即可。</p><button class="primary" id="copy-question">复制问题</button><p id="copy-status" role="status"></p><details><summary>问题全文</summary><textarea id="request-text" readonly>${esc(requestText)}</textarea></details>`,'ask');}
function showAddProfile(){requestText='请帮我维护 China Atlas 人物库。请维护已连接的 China Atlas 源项目，并保留已有个人笔记。请根据我提供的人物、地区或链接，查阅官方履历并补充人物、职务层级与任期，保留来源和日期精度。省委、市委与相应政府须分开记录；历史任职不进入当前权力图。同地经历、同期同机构与明确公开交往分开处理，不推断私人关系。保留已有笔记和任免历史。';showDetail(`<span class="pill">补充资料</span><h2 class="detail-title">下一位人物，从这里加入</h2><label for="ask-question">人物、地区或官方资料链接</label><textarea id="ask-question" placeholder="例如：补充山东省委班子；或者粘贴某位官员的履历链接…">${route==='regions'?esc(place(regionId)?.name+'：'):''}</textarea><p class="note">复制后发到当前 Codex 对话，由 AI 查证并维护数据库。</p><button class="primary" id="copy-question">复制维护请求</button><p id="copy-status" role="status"></p><details><summary>请求全文</summary><textarea id="request-text" readonly>${esc(requestText)}</textarea></details>`,'ask');}
function showEvidence(e){const text=v=>Array.isArray(v)?v.join('\n'):typeof v==='object'?JSON.stringify(v):v;showDetail(`<span class="pill">${isPublicAtlas()?'来源':'本地保存'} · 核对摘录</span><h2 class="detail-title">${esc(e.title)}</h2><p class="note">核对于 ${esc(e.accessed_at||e.retrieved_at||'日期未录入')}${e.published_at?' · 发布于 '+esc(e.published_at):''}${e.event_date?' · 事件日期 '+esc(e.event_date):''}</p><p>${external(e.url,'打开原文')}</p>${e.evidence_excerpt?`<blockquote>${esc(text(e.evidence_excerpt))}</blockquote>`:''}${e.verified_facts||e.basis?`<h3>用于核对的事实</h3>${paragraphs(text(e.verified_facts||e.basis))}`:''}<p class="note">这是研究时保存的摘录与核对记录，不是整篇网页的替代品。</p>`,'evidence');}
function toast(message){$('toast').textContent=message;$('toast').style.display='block';setTimeout(()=>$('toast').style.display='none',4200);}
async function api(path,body){if(isPublicAtlas())return publicAPI(path,body);const r=await fetch('/api/'+path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body===true?{}:body)});let data;try{data=await r.json();}catch{throw new Error('本地服务返回了无法读取的内容。');}if(!r.ok)throw new Error(zh(data.error)||'本地服务未能完成请求。');return data;}
async function reloadAtlas(){atlas=await api('atlas');render();}
async function getNews(){try{news=await api('news');if(route==='changes'&&$('news-panel'))$('news-panel').innerHTML=newsHTML();if(news.refreshing)setTimeout(getNews,1800);}catch(e){news={...news,loading:false,error:e.message};if(route==='changes'&&$('news-panel'))$('news-panel').innerHTML=newsHTML();}}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(await navigationClick(b)||await portableClick(b)||regionClick(b)||await registryClick(b)||await networkClick(b))return;if(b.dataset.evidence){openAtlasEvidence(b.dataset.evidence);}else if(b.id==='add-profile-request'){showAddProfile();}else if(b.dataset.person)showPerson(b.dataset.person);else if(b.dataset.personMap)showPersonMap(b.dataset.personMap);else if(b.dataset.org)showOrg(b.dataset.org);else if(b.dataset.guide)showGuide(b.dataset.guide);else if(b.dataset.document)showDocument(b.dataset.document);else if(b.dataset.openDocument){await api('documents/open',{id:b.dataset.openDocument});toast('已打开原课件。');}else if(b.dataset.saveNote){b.disabled=true;await api('notes',{person_id:b.dataset.saveNote,note:$('person-note').value});person(b.dataset.saveNote).personal_note=$('person-note').value;rememberReadingPosition();toast('笔记已保存。');b.disabled=false;}else if(b.dataset.viewOrgPeople){rememberReadingPosition();peopleOrg=b.dataset.viewOrgPeople;peopleLevel=peopleTrack=peopleStatus=peoplePlace='all';peopleRegionMode='any';peopleSector=peopleVerification='all';focus='all';query='';$('search').value='';leaveDetailForRoute('people',true);}else if(b.dataset.ask){const [kind,id]=b.dataset.ask.split(':');showAsk(kind,id);}else if(b.dataset.graphFocus){showDetail(connectionPanel(b.dataset.graphFocus),'org');}else if(b.dataset.clearGraph){graphFocus='';render();}else if(b.dataset.focus){focus=b.dataset.focus;document.querySelectorAll('[data-focus]').forEach(x=>x.classList.toggle('selected',x.dataset.focus===focus));render();}else if(b.id==='refresh-news'){b.disabled=true;await api('news/refresh',{});await getNews();}else if(b.id==='copy-question'){const text=requestText+'\n\n我的问题： '+$('ask-question').value;$('request-text').value=text;try{await navigator.clipboard.writeText(text);$('copy-status').textContent='已复制，粘贴到当前 Codex 对话即可。';}catch{$('request-text').parentElement.open=true;$('request-text').select();$('copy-status').textContent='请选中并复制下方问题。';}}else if(b.classList.contains('close'))closeAtlasDetail();}catch(err){b.disabled=false;toast(err.message);}});
document.addEventListener('change',e=>{const id=e.target.id;if(id==='region-picker'){goRegion(e.target.value);}else if(id==='region-sector'){regionSector=e.target.value;render();}else if(id==='region-verification'){regionVerification=e.target.value;render();}else if(id==='news-scope'){newsScope=e.target.value;$('news-panel').innerHTML=newsHTML();}else if(id==='diagram-mode'){graphMode=e.target.value;graphFocus='';render();}else if(id==='network-person'){changeNetworkPerson(e.target.value);}else if(id==='network-kind'){networkKind=e.target.value;render();}else if(id==='network-place'){goNetwork(null,e.target.value==='all'?null:e.target.value);}else if(id==='graph-relation'){graphRelation=e.target.value;render();}else if(id.startsWith('people-')){if(id==='people-sector')peopleSector=e.target.value;if(id==='people-verification')peopleVerification=e.target.value;if(id==='people-level')peopleLevel=e.target.value;if(id==='people-track')peopleTrack=e.target.value;if(id==='people-status')peopleStatus=e.target.value;if(id==='people-org')peopleOrg=e.target.value;if(id==='people-place')peoplePlace=e.target.value;if(id==='people-region-mode')peopleRegionMode=e.target.value;render();}});
document.addEventListener('input',e=>{if(e.target.id==='network-compare-search')filterComparisonChoices(e.target.value);});
$('search').addEventListener('input',e=>{query=e.target.value.trim();render();});
window.addEventListener('hashchange',()=>{if(navigationReady)handleAtlasNavigation();else render();});
$('detail').addEventListener('click',e=>{if(e.target===$('detail')){const r=$('detail').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeAtlasDetail();}});
async function boot(){loadPortraits();try{atlas=await api('atlas');initializeLayout();installAtlasNavigation();if(!isPublicAtlas()){getNews();getReviews();}}catch(e){$('content').innerHTML=`<p class="error">${esc(e.message)} 请刷新重试。</p>`;}}
boot();
