'use strict';
let networkTrail=[];
let networkPerson='xi-jinping',networkKind='all',networkPlace='all',peoplePlace='all';
const place=id=>(atlas.locations||[]).find(p=>p.id===id);
function postPlaces(p){const ids=new Set(p.location_ids||[]);let todo=[...ids];while(todo.length){const parent=place(todo.pop())?.parent_id;if(parent&&!ids.has(parent)){ids.add(parent);todo.push(parent);}}return [...ids];}
let careerIndexAtlas=null,careerByPerson=new Map(),careerById=new Map();
function ensureCareerIndex(){if(careerIndexAtlas===atlas)return;careerIndexAtlas=atlas;careerByPerson=new Map();careerById=new Map();for(const post of atlas.career_posts||[]){if(!careerByPerson.has(post.person_id))careerByPerson.set(post.person_id,[]);careerByPerson.get(post.person_id).push(post);careerById.set(post.id,post);}}
const careerPosts=id=>{ensureCareerIndex();return careerByPerson.get(id)||[];};
function groupPlaceLink(group,a,b){ensureCareerIndex();const [from,to]=[a,b].sort();const posts=group.post_ids.map(id=>careerById.get(id)).filter(p=>p&&(p.person_id===from||p.person_id===to));return {id:'place~'+group.location_id+'~'+from+'~'+to,type:'same_place',from,to,location_ids:[group.location_id],post_ids:posts.map(p=>p.id),source_ids:[...new Set(posts.flatMap(p=>p.source_ids))]};}
function expandedPlaceLinks(id){return (atlas.place_groups||[]).filter(g=>g.person_ids.includes(id)).flatMap(g=>g.person_ids.filter(other=>other!==id).map(other=>groupPlaceLink(g,id,other)));}
function findNetworkLink(id){const stored=(atlas.career_links||[]).find(l=>l.id===id);if(stored)return stored;const [prefix,location,a,b,...extra]=id.split('~');const group=(atlas.place_groups||[]).find(g=>g.location_id===location);return prefix==='place'&&!extra.length&&a!==b&&group?.person_ids.includes(a)&&group.person_ids.includes(b)?groupPlaceLink(group,a,b):null;}
const personPlaces=id=>person(id)?servicePlaces(person(id)):[...new Set(careerPosts(id).flatMap(postPlaces))].filter(id=>id!=='china');
const linkLabels={co_service:'同机构 · 确定同期',possible_overlap:'同机构 · 时间待核',same_place:'同地经历',public_contact:'公开活动交集',documented_cowork:'公开材料明确记载共事'};
const linkPriority={documented_cowork:0,co_service:1,public_contact:2,possible_overlap:3,same_place:4};
const byLinkEvidence=(a,b)=>(linkPriority[a.type]??9)-(linkPriority[b.type]??9)||(b.end||b.date||'').localeCompare(a.end||a.date||'')||a.id.localeCompare(b.id);
function pairLinks(a,b){
 if(a===b||!person(a)||!person(b))return [];
 const direct=(atlas.career_links||[]).filter(l=>(l.from===a&&l.to===b)||(l.from===b&&l.to===a));
 const grouped=(atlas.place_groups||[]).filter(g=>g.person_ids.includes(a)&&g.person_ids.includes(b)).map(g=>groupPlaceLink(g,a,b));
 return [...direct,...grouped].sort(byLinkEvidence);
}
function comparisonBody(a,b){
 const first=person(a),second=person(b);if(!first||!second||a===b)return '<p class="empty">请选择两个不同的人物。</p>';
 const links=pairLinks(a,b),shared=new Set(links.flatMap(l=>l.post_ids||[]));
 const columns=[first,second].map(p=>`<section class="comparison-person"><button class="text-button" data-person="${esc(p.id)}"><h3>${esc(personLabel(p))} ↗</h3></button><p class="note">${esc(mainRole(p))}</p>${careerPosts(p.id).slice().sort((a,b)=>(a.start||'9999').localeCompare(b.start||'9999')).map(post=>`<div class="comparison-post ${shared.has(post.id)?'shared-post':''}">${postCard(post)}</div>`).join('')||'<p class="note">尚未录入结构化履历。</p>'}</section>`).join('');
 return `<span class="pill">两人履历对照</span><h2 class="detail-title">${esc(first.name)} ↔ ${esc(second.name)}</h2><p class="note">比较全部已录入经历，不受当前地区、搜索或关系筛选限制。</p><div class="comparison-links">${links.map(l=>`<button data-link="${esc(l.id)}"><span class="badge">${esc(linkLabels[l.type]||l.type)}</span><strong>${esc(l.organization_name||(l.location_ids||[]).map(id=>place(id)?.name||id).join('、')||l.label||'公开事件')}</strong><small>${l.start?esc(l.start)+' — '+esc(l.end):esc(l.date||'不同时间也可能同地')} · 查看依据 →</small></button>`).join('')||'<p class="empty">目前没有已录入的交集。这表示资料中没有找到，不能据此判断两人没有联系。</p>'}</div><p class="note">着色履历支持上方至少一项交集；同地不等于同期，同期不等于私人熟识。</p><div class="comparison-grid">${columns}</div>`;
}
function showComparison(id){const [a,b,...extra]=String(id).split('~');if(extra.length||a===b||!person(a)||!person(b))return;showDetail(comparisonBody(a,b),'comparison');}
function compareControls(p){return `<details class="network-compare"><summary>查两人的履历交集</summary><div class="compare-controls">${personPicker('compare','与 '+p.name+' 对照')}<button class="primary" data-compare-from="${esc(p.id)}">比较两人 →</button></div></details>`;}
function profileCareerTimeline(p){const posts=careerPosts(p.id).slice().sort((a,b)=>(a.start||'9999').localeCompare(b.start||'9999'));const bio=(p.bio||[]).map(b=>`<li><time>${esc(T(b,'years'))}</time><p>${esc(T(b,'role'))}</p>${sources(b.source_ids)}</li>`).join('');return `<section class="profile-careers"><h3>任职时间轴</h3>${posts.length?`<p class="note compact-note">${posts.length} 段已录入经历 · 未知任期不补造，资料状态见各段说明。</p>${posts.map(postCard).join('')}${bio?`<details class="sources"><summary>其他公开履历片段</summary><ol class="timeline">${bio}</ol></details>`:''}`:bio?`<ol class="timeline">${bio}</ol>`:'<p class="note">暂未录入有出处的履历片段。</p>'}</section>`;}
const displayPeriod=p=>p.start&&p.end?p.start+' — '+p.end:p.end?'离任 '+p.end:(p.start?p.start+' 起 · ':'')+(p.is_current?'在任':p.status==='former'?'曾任':'历史记录 · 当前状态待核');
function postCard(p){const evidence=p.as_of_date||p.latest_confirmed_at||p.current_evidence_date,uncertain={conflicting:'来源冲突',unverified:'待核实',directory_only:'名册列示 · 任职待复核'}[p.verification_status];return `<article class="career-post"><div><strong>${esc(p.organization_name)}</strong><time>${esc(displayPeriod(p))}</time></div>${uncertain?`<span class="badge profile-material-warning">${esc(uncertain)}</span>`:''}<p>${esc(p.title)}</p>${evidence?`<small class="career-evidence-date">资料截至 ${esc(evidence)}</small>`:''}<div class="place-tags">${(p.location_ids||[]).map(id=>`<button data-place="${esc(id)}">${esc(place(id)?.name||id)}</button>`).join('')}</div><details class="career-reference"><summary>资料与来源</summary>${p.date_note||p.note?`<p class="note">${esc(p.date_note||p.note)}</p>`:''}${sources(p.source_ids,true)}</details></article>`;}
function networkLinks(id){return [...(atlas.career_links||[]),...((networkKind==='all'||networkKind==='same_place')?expandedPlaceLinks(id):[])].filter(l=>(l.from===id||l.to===id)&&(networkKind==='all'||(networkKind==='co_service'?['co_service','possible_overlap'].includes(l.type):l.type===networkKind))&&(networkPlace==='all'||inheritedPlaces(l.location_ids||[]).includes(networkPlace)));}
function showLink(id){const l=findNetworkLink(id);if(!l)return;const posts=(l.post_ids||[]).map(id=>atlas.career_posts.find(p=>p.id===id)).filter(Boolean);showDetail(`<span class="pill">${esc(linkLabels[l.type]||l.type)}</span><h2 class="detail-title">${esc(person(l.from)?.name)} ↔ ${esc(person(l.to)?.name)}</h2>${l.organization_name?`<p class="level-band">${esc(l.organization_name)}</p>`:''}${l.description?paragraphs(l.description):''}${l.type==='co_service'?`<p>按任期的日期精度保守计算，至少重合：${esc(l.start)} 至 ${esc(l.end)}。这是可确认的交集，不是完整共事任期。</p>`:''}${l.type==='possible_overlap'?'<p>日期精度有限，或两段任期只在交接日相接，暂不能确认同期任职。</p>':''}${l.type==='same_place'?'<p>两人都曾在该地区任职；可以是不同时间、不同单位。</p>':''}${l.date?`<p>公开事件日期：${esc(l.date)}</p>`:''}<div class="link-evidence">${posts.map(p=>`<h3>${esc(person(p.person_id)?.name)}</h3>${postCard(p)}`).join('')}</div><p class="note">任职交集和公开同场不直接说明私人关系、熟识程度或任用原因。</p>${sources(l.source_ids)}<div class="detail-actions"><button data-network-person="${esc(l.from)}">以 ${esc(person(l.from)?.name)} 为中心</button><button data-network-person="${esc(l.to)}">以 ${esc(person(l.to)?.name)} 为中心</button></div>`,'network');}
function neighborCard(id,links){const p=person(id);links=links.slice().sort(byLinkEvidence);const strongest=links[0];return `<article class="neighbor-card ${strongest.type}"><button class="neighbor-name" data-network-person="${esc(id)}"><strong>${esc(personLabel(p))}</strong><small>${esc(mainRole(p))}</small></button><div class="neighbor-links">${links.map(l=>`<button data-link="${esc(l.id)}"><span class="badge">${esc(linkLabels[l.type])}</span> ${esc(l.organization_name||(l.location_ids||[]).map(id=>place(id)?.name||id).join('、')||l.label||'公开事件')} ${l.start?`<small>${esc(l.start.slice(0,4))}${l.start.slice(0,4)!==l.end.slice(0,4)?'—'+esc(l.end.slice(0,4)):''}</small>`:''} →</button>`).join('')}</div></article>`;}
function drawNetwork(){let p=person(networkPerson)||atlas.people[0];networkPerson=p.id;const eligible=atlas.people.filter(match);const links=networkLinks(p.id),neighbors=new Map();links.forEach(l=>{const id=l.from===p.id?l.to:l.from;if(!person(id)||!eligible.some(p=>p.id===id))return;if(!neighbors.has(id))neighbors.set(id,[]);neighbors.get(id).push(l);});const locations=(atlas.locations||[]).filter(l=>l.id!=='china');const footprint=careerPosts(p.id).filter(post=>networkPlace==='all'||postPlaces(post).includes(networkPlace));
 return `${networkTrail.length?`<div class="network-path"><button id="network-back">← 返回 ${esc(person(networkTrail[networkTrail.length-1].person)?.name||'上一位')}</button><small>${networkTrail.map(s=>person(s.person)?.name||s.person).map(esc).join(' → ')} → ${esc(p.name)}</small></div>`:''}<div class="network-tools">${personPicker('center','以谁为中心')}${selectBox('network-kind','看哪种联系',[['all','所有已录入联系'],['co_service','同一机构的任期交集'],['same_place','同地经历'],['public_contact','公开活动交集']],networkKind)}${selectBox('network-place','地区',[['all','所有地区'],...locations.map(l=>[l.id,l.name])],networkPlace)}<button id="network-random">随便看看 ↝</button></div><div class="network-center"><div><span class="mini-label">${current(p).length?'现任资料':personStatus(p)==='uncertain'?'任职状态待复核':'历史人物'}</span><h2>${esc(p.name)} <small>${esc(p.name_en||'')}</small></h2><p>${esc(mainRole(p))}</p></div><button data-person="${esc(p.id)}">完整人物档案 →</button></div>${compareControls(p)}<div class="network-summary"><span>${neighbors.size} 条关联档案</span><p>有任期或活动依据的交集优先。点关系查看原文；同地经历不代表私人熟识。</p></div><div class="neighbor-grid">${[...neighbors].sort((a,b)=>(linkPriority[a[1].slice().sort(byLinkEvidence)[0].type]??9)-(linkPriority[b[1].slice().sort(byLinkEvidence)[0].type]??9)||person(a[0]).name.localeCompare(person(b[0]).name,'zh-CN')).map(([id,links])=>neighborCard(id,links)).join('')||'<p class="empty">这个筛选下暂未录入交集。可以换一个地区、人物或关系类型。</p>'}</div><section class="map-section footprint"><div class="section-title"><h2>${esc(p.name)} 的地区足迹</h2><span>只列已核对的履历片段</span></div><div class="place-tags">${personPlaces(p.id).map(id=>`<button data-place="${esc(id)}">${esc(place(id)?.name||id)}</button>`).join('')}</div>${footprint.sort((a,b)=>(a.start||'').localeCompare(b.start||'')).map(postCard).join('')||'<p class="note">尚无结构化履历。可以先阅读人物档案中的公开生平。</p>'}</section><section class="place-directory"><div class="section-title"><h2>从一个地区开始</h2><span>省 → 市 → 区县，可继续扩展</span></div><div class="place-grid">${locations.filter(l=>atlas.people.some(p=>personPlaces(p.id).includes(l.id))).map(l=>`<button data-place="${esc(l.id)}"><strong>${esc(l.name)}</strong><span>${atlas.people.filter(p=>personPlaces(p.id).includes(l.id)).length} 条人物档案 →</span></button>`).join('')}</div></section>`;
}
function rememberNetwork(){if(route==='network'){networkTrail.push({person:networkPerson,place:networkPlace,kind:networkKind,query});if(networkTrail.length>12)networkTrail.shift();}else networkTrail=[];}
function changeNetworkPerson(id){if(id!==networkPerson)rememberNetwork();networkPerson=id;query='';$('search').value='';render();}
function goNetwork(id,location){rememberReadingPosition();if((id&&id!==networkPerson)||(location&&location!==networkPlace))rememberNetwork();if(id)networkPerson=id;if(location){networkPlace=location;networkKind='all';const candidate=atlas.people.find(p=>personPlaces(p.id).includes(location));if(!personPlaces(networkPerson).includes(location)&&candidate)networkPerson=candidate.id;}else{networkPlace='all';networkKind='all';}if($('detail').open)$('detail').close();query='';$('search').value='';locationHash('network');}
function locationHash(hash){if(navigationReady)leaveDetailForRoute(hash,true);else if(location.hash==='#'+hash)render();else location.hash=hash;}
async function networkClick(b){if(b.dataset.compareFrom){const other=$('network-compare')?.value;if(!other){toast('先选择另一位人物。');return true;}showComparison(b.dataset.compareFrom+'~'+other);return true;}if(b.dataset.networkPerson){if(route==='network'){if($('detail').open){rememberReadingPosition();networkPerson=b.dataset.networkPerson;leaveDetailForRoute('network?center='+encodeURIComponent(networkPerson)+(networkPlace!=='all'?'&place='+encodeURIComponent(networkPlace):''),true);}else changeNetworkPerson(b.dataset.networkPerson);}else goNetwork(b.dataset.networkPerson);return true;}if(b.dataset.place){goNetwork(null,b.dataset.place);return true;}if(b.dataset.link){showLink(b.dataset.link);return true;}if(b.id==='network-back'){const previous=networkTrail.pop();if(previous){networkPerson=previous.person;networkPlace=previous.place;networkKind=previous.kind;query=previous.query;$('search').value=query;render();}return true;}if(b.id==='network-random'){const candidates=atlas.people.filter(p=>p.id!==networkPerson&&(networkPlace==='all'||personPlaces(p.id).includes(networkPlace))&&((atlas.place_groups||[]).some(g=>g.person_ids.includes(p.id))||(atlas.career_links||[]).some(l=>l.from===p.id||l.to===p.id)));if(candidates.length){changeNetworkPerson(candidates[Math.floor(Math.random()*candidates.length)].id);}else toast('这个筛选下暂无其他人物。');return true;}return false;}

function filterComparisonChoices(value){const input=$('network-compare-search');if(input){input.value=value;updateSearchInput(input);}}
