'use strict';
let regionId='jining',regionService='current',regionDepth='direct',peopleRegionMode='any';
try{regionId=localStorage.getItem('china-atlas-region')||regionId;}catch{}
const priorityPlaces=['shandong','jining','jinan','qingdao','beijing','shanghai'];
function inheritedPlaces(ids){const result=new Set(ids),todo=[...result];while(todo.length){const parent=place(todo.pop())?.parent_id;if(parent&&!result.has(parent)){result.add(parent);todo.push(parent);}}return [...result].filter(id=>id!=='china');}
function careerStatus(post){return post.end||post.status==='former'?'former':post.is_current&&post.checked_at?'current':'historical';}
function servicePlaces(p,mode='any'){
 const matches=status=>mode==='any'||(mode==='current'?status==='current':mode==='past'?status==='former':!['current','former'].includes(status));
 const roles=p.roles.filter(r=>matches(r.status)).flatMap(r=>org(r.org_id)?.location_ids||[]);
 const posts=careerPosts(p.id).filter(post=>matches(careerStatus(post))).flatMap(post=>post.location_ids||[]);
 return inheritedPlaces([...roles,...posts]);
}
function localPlaces(){return (atlas.locations||[]).filter(l=>!['china','central'].includes(l.id)).sort((a,b)=>{const ai=priorityPlaces.indexOf(a.id),bi=priorityPlaces.indexOf(b.id);return (ai<0?999:ai)-(bi<0?999:bi)||a.name.localeCompare(b.name,'zh-CN');});}
function directPlaces(ids){return ids.filter(id=>!ids.some(other=>other!==id&&inheritedPlaces([other]).includes(id)));}
function scopedPlaces(ids){return regionDepth==='all'?inheritedPlaces(ids):directPlaces(ids);}
function directServicePlaces(p,mode='any'){const matches=status=>mode==='any'||(mode==='current'?status==='current':mode==='past'?status==='former':!['current','former'].includes(status));return [...new Set([...p.roles.filter(r=>matches(r.status)).flatMap(r=>directPlaces(org(r.org_id)?.location_ids||[])),...careerPosts(p.id).filter(post=>matches(careerStatus(post))).flatMap(post=>directPlaces(post.location_ids||[]))])];}
function regionPeople(id,mode='any',includeChildren=true){return atlas.people.filter(p=>(includeChildren?servicePlaces(p,mode):directServicePlaces(p,mode)).includes(id));}
function regionRoles(p,id,mode){return p.roles.filter(r=>(mode==='all'||(mode==='current'?r.status==='current':r.status!=='current'))&&scopedPlaces(org(r.org_id)?.location_ids||[]).includes(id));}
function localRoleLine(p,id,mode){const roles=regionRoles(p,id,mode);if(roles.length)return roles.map(r=>(r.status==='current'?'':r.status==='former'?'曾任 ':'历史记录 ')+T(r,'title')).join(' · ');const posts=careerPosts(p.id).filter(post=>scopedPlaces(post.location_ids||[]).includes(id)&&(mode==='all'||(mode==='current'?careerStatus(post)==='current':careerStatus(post)==='former')));return posts.map(post=>(careerStatus(post)==='former'?'曾任 ':'')+post.title).slice(0,3).join(' · ');}
function regionalOrder(p,id,mode){const titles=regionRoles(p,id,mode).map(r=>T(r,'title'));const tests=[/(省委|市委)书记$/,/(省长|市长)$/,/(省委|市委)副书记$/,/(人大常委会|人民代表大会常务委员会)主任$/,/(政协|政治协商会议).*主席$/,/(常务副省长|常务副市长)$/,/(副省长|副市长)$/];for(let i=0;i<tests.length;i++)if(titles.some(t=>tests[i].test(t)&&(i!==1||!/(副|代理|代市长)/.test(t))&&(i!==3&&i!==4||!t.includes('副'))))return i;return 20;}
function regionalCaption(p,id,mode){if(band(p)!=='unclassified')return bandLabel(p);const types={prefecture:'地级市岗位',province:'省级岗位',municipality:'直辖市岗位',subprovincial:'副省级城市岗位',district:'区县岗位'};let ids=regionRoles(p,id,mode).flatMap(r=>directPlaces(org(r.org_id)?.location_ids||[]));if(!ids.length)ids=careerPosts(p.id).filter(post=>scopedPlaces(post.location_ids||[]).includes(id)&&(mode==='all'||careerStatus(post)===(mode==='current'?'current':'former'))).flatMap(post=>directPlaces(post.location_ids||[]));const labels=[...new Set(ids.map(pid=>types[place(pid)?.type]||'地方岗位'))];return (labels.join(' / ')||'地方岗位')+' · 个人级别待核';}
function regionalCard(p,id,mode){const currentHere=(regionDepth==='all'?servicePlaces(p,'current'):directServicePlaces(p,'current')).includes(id);return `<article class="regional-person"><button class="regional-profile" data-person="${esc(p.id)}"><span class="mini-label">${esc(regionalCaption(p,id,mode))}${currentHere?' · 现任在此':' · 过往经历'}</span><h3>${esc(p.name)} <small>${esc(p.name_en||'')}${p.birth_year?' · '+esc(p.birth_year)+'年生':''}</small></h3><p>${esc(localRoleLine(p,id,mode)||mainRole(p))}</p>${!currentHere&&current(p).length?`<small>现任：${esc(mainRole(p))}</small>`:''}</button><div class="regional-card-actions"><button data-network-person="${esc(p.id)}">关系与足迹 ↔</button><small>核对 ${esc(p.checked_at||'日期待核')}</small></div></article>`;}
function placeBreadcrumb(id){const chain=[];let value=place(id),seen=new Set();while(value&&!seen.has(value.id)&&value.id!=='china'){seen.add(value.id);chain.unshift(value);value=place(value.parent_id);}return chain.map((l,i)=>`<button data-region="${esc(l.id)}">${esc(l.name)}</button>${i<chain.length-1?'<span> / </span>':''}`).join('');}
function drawRegions(){const locations=localPlaces();if(!place(regionId))regionId=locations[0]?.id;const location=place(regionId);if(!location)return '<p class="empty">地方资料正在整理。</p>';const mode=regionService==='all'?'any':regionService;const scoped=(mode='any')=>regionPeople(regionId,mode,regionDepth==='all');const all=scoped(),people=scoped(mode).filter(p=>match(p)||careerPosts(p.id).some(match)).sort((a,b)=>regionalOrder(a,regionId,regionService)-regionalOrder(b,regionId,regionService)||bands.findIndex(([id])=>id===band(a))-bands.findIndex(([id])=>id===band(b))||a.name.localeCompare(b.name,'zh-CN'));const institutions=atlas.institutions.filter(o=>(o.location_ids||[]).includes(regionId)&&members(o.id).length);const descendants=locations.filter(l=>l.parent_id===regionId&&regionPeople(l.id).length);const ancestors=place(location.parent_id);const postCount=(atlas.career_posts||[]).filter(p=>postPlaces(p).includes(regionId)).length;
 return `<div class="region-switcher" aria-label="常看地区">${locations.filter(l=>priorityPlaces.includes(l.id)).map(l=>`<button data-region="${esc(l.id)}" class="${l.id===regionId?'selected':''}">${esc(l.name)}</button>`).join('')}${selectBox('region-picker','更多地区',locations.map(l=>[l.id,l.name]),regionId)}</div><section class="region-heading"><div><div class="region-breadcrumb">${placeBreadcrumb(regionId)}</div><h2>${esc(location.name)}<small>${esc(location.name_en||'')}</small></h2><p>${scoped('current').length} 位现任人物 · ${scoped('past').length} 位有过往经历 · ${postCount} 段任职记录</p></div><div class="detail-actions"><a class="export-link" href="/api/regions/export?id=${encodeURIComponent(regionId)}" download="china-atlas-${esc(regionId)}.json">保存本地区资料 ↓</a><button data-region-network="${esc(regionId)}">看地区关系网 ↔</button></div></section>${descendants.length?`<div class="subregions"><span>往下看</span>${descendants.map(l=>`<button data-region="${esc(l.id)}">${esc(l.name)} <small>${regionPeople(l.id).length} 人</small> →</button>`).join('')}</div>`:''}${descendants.length?`<div class="scope-toggle"><span>范围</span><button data-region-depth="direct" class="${regionDepth==='direct'?'selected':''}">本级机构</button><button data-region-depth="all" class="${regionDepth==='all'?'selected':''}">包含下辖地区</button></div>`:''}<div class="region-tabs" role="group" aria-label="地方任职状态">${[['current','现任在这里'],['past','曾在这里工作'],['all','全部经历']].map(([id,label])=>`<button data-region-service="${id}" class="${regionService===id?'selected':''}">${label}</button>`).join('')}<span>${people.length} 位</span></div><div class="regional-grid">${people.map(p=>regionalCard(p,regionId,regionService)).join('')||'<p class="empty">当前筛选暂无已核实人物。可以看全部经历，或切换地区。</p>'}</div>${institutions.length?`<section class="map-section regional-institutions"><div class="section-title"><h2>本级机构</h2><span>人物可以在多个机构任职</span></div><div class="org-grid">${institutions.map(o=>orgCard(o.id)).join('')}</div></section>`:''}<details class="coverage-note"><summary>资料范围与保存方式</summary><p class="note">这是逐步核实的精选库，尚非完整班子名单。现任岗位与过往经历分别呈现；有下辖地区时，可切换本级与全部范围。导出文件包含下辖地区的记录。${isPublicAtlas()?'地区 JSON 只导出公开档案、履历和来源。个人笔记请单独导出。':'地区 JSON 包含人物档案、笔记、履历与来源，任免修改历史仍保留在本机数据库。'}</p><p class="note">${esc((atlas.regional_coverage||[]).find(c=>c.location_id===regionId)?.note||'先从主要负责人和有来源的履历片段开始，之后逐步补充。')}</p><button id="add-profile-request">补充这个地区的人物 →</button></details>`;
}
function goRegion(id){rememberReadingPosition();regionId=id;regionService='current';regionDepth='direct';try{localStorage.setItem('china-atlas-region',id);}catch{}query='';$('search').value='';if($('detail').open)$('detail').close();locationHash('regions?region='+encodeURIComponent(id));}
function regionClick(b){if(b.dataset.region){goRegion(b.dataset.region);return true;}if(b.dataset.regionDepth){regionDepth=b.dataset.regionDepth;render();return true;}if(b.dataset.regionService){regionService=b.dataset.regionService;render();return true;}if(b.dataset.regionNetwork){goNetwork(null,b.dataset.regionNetwork);return true;}if(b.id==='clear-people-filters'){peopleLevel=peopleTrack=peopleStatus=peopleOrg=peoplePlace='all';peopleRegionMode='any';focus='all';query='';$('search').value='';render();return true;}return false;}
