'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const el={value:'',addEventListener(){},open:false};
const ctx=vm.createContext({document:{getElementById:()=>el,addEventListener(){},querySelectorAll:()=>[],querySelector:()=>el},window:{addEventListener(){}},location:{hash:'#people'},console,URL,URLSearchParams,Set,Map,setTimeout,requestAnimationFrame(){}});
for(const f of ['portable.js','navigation.js','graph.js','registry-ui.js','network.js','regions.js','portraits.js','personnel.js','departments.js','search.js','profile.js','app.js'])vm.runInContext(fs.readFileSync(path.join(root,'web',f),'utf8').replace(/boot\(\);\s*$/,''),ctx);
const run=s=>vm.runInContext(s,ctx);
ctx.fixture={people:[{id:'a',name:'甲',roles:[{org_id:'old',title:'副主任',status:'former'},{org_id:'new',title:'主任',status:'current'}],bio:[]},{id:'b',name:'乙',roles:[],bio:[]}],institutions:[{id:'old',name:'旧部门',sector:'development',location_ids:['jining']},{id:'new',name:'新部门',sector:'housing',location_ids:['jinan']},{id:'court',name:'法院',sector:'court',location_ids:['jining']}],locations:[{id:'jining',name:'济宁',parent_id:'shandong'},{id:'jinan',name:'济南',parent_id:'shandong'},{id:'shandong',name:'山东',parent_id:'china'}],sources:[{id:'s',url:'https://example.gov.cn/s',title:'原文'}],career_posts:[{id:'post',person_id:'b',organization_id:'old',title:'处长',status:'former',start:'2020',end:'2021',location_ids:['jining'],source_ids:['s']}],status_events:[],career_links:[],person_connections:[],events:[],relations:[],guides:[],rank_mapping:[],regional_coverage:[]};
run('atlas=fixture');
assert.equal(run("statusBadges(person('a'))"),'');
assert.equal(run("matchesStatusEvent(person('a'),'retired')"),false,'No recorded event never means retirement');
assert.equal(run("matchesStatusEvent(person('a'),'none')"),true);
assert.deepEqual(Array.from(run("departmentPeople('old','current').map(p=>p.id)")),[],'Current elsewhere does not mean current here');
assert.deepEqual(Array.from(run("departmentPeople('old','past').map(p=>p.id)")),['a','b'],'Structured career-only records remain discoverable');
assert.equal(run("departmentGroupFor(org('new'))"),'housing');
assert.equal(run("institutionInArea({id:'unknown',location_ids:[]},'central')"),false,'Missing geography does not imply national agency');
assert.equal(run("institutionInArea(org('old'),'jinan')"),false);
assert.equal(run("institutionInArea(org('old'),'shandong')"),true);
const event=(id,code,category,date='2026-09-21')=>({id,person_id:'a',category,code,label:code,announced_at:date,effective_at:null,description:'原文记录',source_ids:['s'],org_ids:['court'],evidence_status:'verified',reviewed_at:'2026-09-21'});
ctx.fixture.status_events=[event('investigate','investigation_opened','investigation','2026-01-24'),event('party','expelled_party','party_discipline'),event('military','expelled_military','military_status'),event('judicial','referred_for_prosecution','judicial')];
assert.equal(run("matchesStatusEvent(person('a'),'convicted')"),false,'Referral must not imply conviction');
assert.equal(run("matchesStatusEvent(person('a'),'category:party_discipline')"),true);
assert.equal(run("statusBadges(person('a')).includes('investigation_opened')"),false,'Cards show latest announcement; the older investigation stays in history');
assert.equal(run("profileStatusHistory(person('a')).includes('investigation_opened')"),true);
ctx.fixture.status_events.push({...event('appointment','appointed','office_change'),label:'决定甲为旧部门代理主任'});
assert.equal(run("statusFilter().includes('任命／当选')"),true,'Shared action filters use generic labels across people and offices');
assert.equal(run("statusFilter().includes('决定甲为旧部门代理主任')"),false,'A single appointment must not name the shared action filter');
ctx.fixture.status_events.pop();
const correcting={...event('correction','case_dismissed','judicial','2026-09-22'),supersedes_event_ids:['judicial'],evidence_status:'unverified',label:'<script>unsafe()</script>'};
ctx.fixture.status_events.push(correcting);
assert.equal(run("activeStatusEvents('a').some(e=>e.id==='judicial')"),true,'Unverified correction must not hide a sourced event');
assert.equal(run("profileStatusHistory(person('a')).includes('<script>unsafe()')"),false);
correcting.evidence_status='verified';
assert.equal(run("activeStatusEvents('a').some(e=>e.id==='judicial')"),false,'Explicit verified correction supersedes without deleting history');
assert.equal(run("profileStatusHistory(person('a')).includes('已有明确更正记录')"),true);
assert.equal(run("personStatusEvents('a').length"),5);
const exported=run("publicRegionExport('jining')");
assert.equal(exported.status_events.length,5);
assert.ok(exported.institutions.some(o=>o.id==='court'),'Event institution closure survives regional export');
assert.ok(exported.sources.some(s=>s.id==='s'));
assert.equal(run("publicRegionExport('missing').status_events.length"),0,'No unrelated status records in regional export');
assert.equal(run("person('a').roles[1].status"),'current','Events do not silently mutate office status');
assert.deepEqual(Array.from(run("roleTracks({org_id:'cpc-cmc',title:'中共中央军事委员会副主席'})")),['military','party']);
assert.deepEqual(Array.from(run("roleTracks({org_id:'state-cmc',title:'中华人民共和国中央军事委员会副主席'})")),['military','state']);
console.log('Personnel evidence, correction, regional export and department scope checks passed');
