'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.resolve(__dirname,'..');
const el={value:'',addEventListener(){},open:false,setAttribute(){},showModal(){this.open=true;}};
const ctx=vm.createContext({document:{getElementById:()=>el,addEventListener(){},querySelectorAll:()=>[],querySelector:()=>el},window:{addEventListener(){}},location:{hash:'#people'},console,URL,URLSearchParams,Set,Map,setTimeout,requestAnimationFrame(){}});
for(const f of ['portable.js','navigation.js','graph.js','registry-ui.js','network.js','regions.js','portraits.js','personnel.js','departments.js','app.js','profile.js'])vm.runInContext(fs.readFileSync(path.join(root,'web',f),'utf8').replace(/boot\(\);\s*$/,''),ctx);
const run=s=>vm.runInContext(s,ctx);
ctx.fixture=JSON.parse(fs.readFileSync(path.join(root,'data/atlas.json'),'utf8'));
run('atlas=fixture');
// Simulate the browser's default disclosure state without discarding nested content.
function visibleText(html){let depth=0,text='';for(const token of html.match(/<[^>]*>|[^<]+/g)||[]){if(/^<details\b/.test(token)){depth++;continue;}if(/^<\/details>/.test(token)){depth--;continue;}if(!depth&&!token.startsWith('<'))text+=token+' ';}return text.replace(/\s+/g,' ').trim();}
function profile(id){ctx.id=id;run('showPerson(id)');return el.innerHTML;}
const liu=ctx.fixture.people.find(p=>p.name==='刘瑞峰');
const html=profile(liu.id),visible=visibleText(html);
assert.equal((visible.match(/济宁市城市管理局党组成员、副局长/g)||[]).length,1,'One current job must not repeat as a role, career and CV fragment');
for(const phrase of ['尚未录入专门记录','一般免职或离任不自动标为处分','起始日期未单独核准','as_of_date','未知任期不补造','履历为已核对片段','个人级别未单独核准','任职经历','档案整理于'])assert(!visible.includes(phrase),'Reading view must omit metadata filler: '+phrase);
assert(visible.includes('资料截至 2026-05-21'),'Evidence date stays explicitly qualified');
assert(!visible.includes('2026-05-21 起'),'Evidence date never becomes an appointment date');
assert(visible.includes('市容管理'),'Real responsibilities remain visible');
assert(!visible.includes('承担局党组交办'),'Long duty boilerplate is available on expansion');
assert(html.includes('承担局党组交办'),'Full source-derived duty text is preserved');
assert(html.includes('as_of_date'),'Audit metadata remains behind disclosure');
assert(html.includes('data-evidence='),'Source excerpt navigation remains available');
assert.equal(run('profileStatusHistory(person(id))'),'','Empty event history is omitted, never labelled clean');
const zhu=visibleText(profile('zhu-rongji'));
assert(zhu.includes('任职经历')&&zhu.includes('1998-03 — 2003-03'),'Former leaders retain dated careers');
assert.equal((profile('zhu-rongji').match(/<h4>国务院总理<\/h4>/g)||[]).length,1,'Duplicate historical role and career record are consolidated');
const zhang=visibleText(profile('zhang-youxia'));
assert(zhang.includes('开除党籍（待中央全会追认）'),'Material pending ratification must stay visible');
assert(zhang.includes('开除军籍（此前已决定）'),'Earlier unspecified decision is not redated');
assert(zhang.includes('移送军事检察机关审查起诉'),'Judicial stage stays explicit');
assert(!zhang.includes('已判决有罪'),'Referral is not rendered as a conviction');
const original=JSON.stringify(ctx.fixture);
for(const p of ctx.fixture.people)assert(profile(p.id).includes(p.name.replace(/&/g,'&amp;')),'Every existing identity must render: '+p.id);
assert.equal(JSON.stringify(ctx.fixture),original,'Reading presentation cannot mutate sourced data or notes');
ctx.synthetic={people:[{id:'a',name:'同名',roles:[{org_id:'department',title:'主任',status:'current',verification_status:'conflicting',as_of_date:'2026-05-01',source_ids:['s']}],possible_identity_ids:['b'],identity_note:'同名身份尚待确认。',personal_note:'<script>Keep my note</script>',bio:[]},{id:'b',name:'同名',roles:[],bio:[]}],institutions:[{id:'department',name:'某部门',location_ids:['city']}],sources:[{id:'s',title:'来源',url:'https://example.gov.cn/person'}],locations:[{id:'city',name:'城市'}],career_posts:[],status_events:[],profile_facts:[{person_id:'a',field:'education',value:'待核学历',evidence_status:'unverified',source_ids:['s']}],career_links:[],person_connections:[],events:[],relations:[],guides:[],rank_mapping:[],regional_coverage:[]};
run('atlas=synthetic');
const ambiguous=profile('a'),ambiguousVisible=visibleText(ambiguous);
assert(ambiguousVisible.includes('来源冲突')&&ambiguousVisible.includes('同名身份待核'),'Real uncertainty is not hidden with generic boilerplate');
assert(ambiguousVisible.includes('待核学历')&&ambiguousVisible.includes('待核实'),'Unverified background remains labelled next to its value');
assert(ambiguous.includes('&lt;script&gt;Keep my note&lt;/script&gt;')&&!ambiguous.includes('<script>'),'Existing notes remain escaped and editable');
assert(ambiguous.includes('data-save-note="a"')&&ambiguous.includes('id="person-note"'),'Existing save and draft selectors are stable');
ctx.synthetic.people[0].roles=[{org_id:'department',title:'主任',status:'former',since:'2010',until:'2012'},{org_id:'department',title:'主任',status:'former',since:'2015',until:'2016'}];
assert.equal(run("profileReadingEntries(person('a')).length"),2,'Separate terms in the same office cannot be merged');
ctx.synthetic.people[0].roles.push({org_id:'department',title:'主任',status:'former'});
assert.equal(run("profileReadingEntries(person('a')).length"),3,'Undated same-source entry cannot attach to the first of two dated terms');
ctx.synthetic.people[0].roles.pop();
ctx.synthetic.career_posts=[{id:'undated-career',person_id:'a',organization_id:'department',title:'主任',status:'former'}];run('careerIndexAtlas=null');
assert.equal(run("profileReadingEntries(person('a')).length"),3,'An undated career compatible with two office terms stays separate');
ctx.synthetic.people[0].roles=[{org_id:'department',title:'主任',status:'former'}];
ctx.synthetic.career_posts=[{id:'career-1',person_id:'a',organization_id:'department',title:'主任',start:'2010',end:'2012'},{id:'career-2',person_id:'a',organization_id:'department',title:'主任',start:'2015',end:'2016'}];run('careerIndexAtlas=null');
assert.equal(run("profileReadingEntries(person('a')).length"),3,'Reverse input order cannot make an undated role pick one career term');
ctx.synthetic.career_posts.pop();run('careerIndexAtlas=null');
assert.equal(run("profileReadingEntries(person('a')).length"),1,'A unique mutually compatible role-career pair can still consolidate');
ctx.synthetic.career_posts=[];run('careerIndexAtlas=null');
ctx.synthetic.people[0].roles=[{org_id:'department',title:'主任',status:'former',since:'2010',until:'2012',source_ids:['s']},{org_id:'department',title:'主任',status:'former',since:'2010',until:'2012',source_ids:['other-source']}];
assert.equal(run("profileReadingEntries(person('a')).length"),2,'Distinct records of the same source type remain separate even with matching dates');
ctx.synthetic.people[0].roles[1]=JSON.parse(JSON.stringify(ctx.synthetic.people[0].roles[0]));
assert.equal(run("profileReadingEntries(person('a')).length"),1,'Exact duplicate rows do not duplicate the reading view');
ctx.synthetic.people[0].focus='负责经济运行；分管综合科。';
assert(profile('a').includes('完整人物说明'),'String-valued focus fields remain readable in both summary and references');
ctx.synthetic.people[0].roles=[{org_id:'department',title:'处长',status:'historical',verification_status:'historical_only',as_of_date:'2020-01-01'}];
const unknown=visibleText(profile('a'));
assert(unknown.includes('历史记录 · 当前状态待核'),'An old appointment with no departure cannot be labelled former or current');
assert(!unknown.includes('现任职务')&&!unknown.includes('曾任'),'Unknown departure is not inferred');
assert(unknown.indexOf('任职经历')<unknown.indexOf('人物概览'),'For people with only historical records, the career timeline explains their role before the overview');
console.log('Compact profile reading, deduplication, real uncertainty, source retention and note safety checks passed');
